# THIS FILE IS AUTOGENERATED BY THE AUTOREGISTRY PLUGIN.
# DO NOT EDIT MANUALLY. ANY CHANGES WILL BE OVERWRITTEN.
#
# Class containing preloaded data entries for the 'Events' registry (Core).

class_name Events

const DUMMY_EVENT: EventEntry = preload("res://data/core/events/dummy_event.tres")

static var ALL: Array[EventEntry] = [DUMMY_EVENT]

static func get_all() -> Array[EventEntry]:
    return ALL
