# THIS FILE IS AUTOGENERATED BY THE AUTOREGISTRY PLUGIN.
# DO NOT EDIT MANUALLY. ANY CHANGES WILL BE OVERWRITTEN.
#
# Class containing preloaded data entries for the 'Scenes' registry.

class_name Scenes

const MAIN: SceneEntry = preload("res://data/registry/scenes/main.tres")

static var ALL: Array[SceneEntry] = [MAIN]

static func get_all() -> Array[SceneEntry]:
    return ALL
