# THIS FILE IS AUTOGENERATED BY THE AUTOREGISTRY PLUGIN.
# DO NOT EDIT MANUALLY. ANY CHANGES WILL BE OVERWRITTEN.
#
# Class containing preloaded data entries for the 'SceneSets' registry (Core).

class_name SceneSets

const DEFAULT: SceneSetEntry = preload("res://data/registry/core/scene_sets/default.tres")

static var ALL: Array[SceneSetEntry] = [DEFAULT]

static func get_all() -> Array[SceneSetEntry]:
    return ALL
