# THIS FILE IS AUTOGENERATED BY THE AUTOREGISTRY PLUGIN.
# DO NOT EDIT MANUALLY. ANY CHANGES WILL BE OVERWRITTEN.
#
# Class containing preloaded data entries for the 'Transitions' registry.

class_name Transitions

const DEFAULT: TransitionEntry = preload("res://data/registry/transitions/default.tres")

static var ALL: Array[TransitionEntry] = [DEFAULT]

static func get_all() -> Array[TransitionEntry]:
    return ALL
